/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'yehuang' at '2/13/17 1:31 PM' with Gradle 2.4
 *
 * @author yehuang, @date 2/13/17 1:31 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
