/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'yehuang' at '2/13/17 1:31 PM' with Gradle 2.4
 *
 * @author yehuang, @date 2/13/17 1:31 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
